services:
  cassandra:
    image: cassandra:5.0
    container_name: cassandra-shop
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=ShopCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data: